version: "3.3"

services:
  app:
    container_name: send-telegram-message
    image: send_telegram_message:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
