version: "3.3"

services:
  app:
    container_name: telegram-flooder
    image: telegram_flooder:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
